# Generated by Django 5.0.7 on 2024-08-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='image',
            field=models.ImageField(default='default.png', upload_to='watches/'),
        ),
    ]
